#!/bin/bash
# read our configuration
source /boot/config/plugins/unbalance/unbalance.cfg

prog="/usr/local/emhttp/plugins/unbalance/unbalance"

# stop it if it's running
killall unbalance > /dev/null 2>&1

# run the app
nohup sudo -H -u $RUNAS bash -c "$prog -port $PORT" > /dev/null 2>&1 &
