name: release

on:
  workflow_dispatch:
    inputs:
      patch:
        description: Patch letter to apply to version.
        type: string
        default: ""

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v4

      - name: set up go
        uses: actions/setup-go@v2
        with:
          go-version: 1.21

      - name: set up node
        uses: actions/setup-node@v4
        with:
          node-version: 18.x

      - name: install node dependencies
        run: |
          pushd ui
          npm install
          popd

      - name: build app
        run: |
          make local
          ls -al
