#!/bin/bash

function error {
  echo -e "$1" >&2
  exit 1
}

UB_RELEASE="release/unBALANCE"
UB_VERSION=$(cat VERSION)
UB_FILE="unBALANCE-$UB_VERSION.tgz"
echo $UB_FILE


if [ -f "$UB_FILE" ]; then
	echo -e "Bundle $UB_FILE already exists. No further actions will be taken." >&2
	exit 0
fi


if ! git diff --quiet; then
	error "There are unsaved changes in your current branch. Please commit changes and try again."
fi

branch_name=$(git symbolic-ref -q HEAD)
branch_name=${branch_name##refs/heads/}
branch_name=${branch_name:-HEAD}

if [[ $branch_name != "master" ]]; then
	error "Can release only from master branch. Switch to master and try again."
fi

git checkout master

UB_RELEASE="release/unBALANCE"
UB_VERSION=$(cat VERSION)
UB_FILE="unBALANCE-$UB_VERSION.tgz"
echo $UB_FILE

rm -rf release && mkdir -p $UB_RELEASE
cp -r dist/* $UB_RELEASE
cp server/diskmv $UB_RELEASE/diskmv
cp -r plugin/event $UB_RELEASE
pushd release 
tar czvf ./$UB_FILE usr 
mv ./$UB_FILE ..
popd

UB_MD5=$(md5sum ./$UB_FILE | cut -d' ' -f1)
echo $UB_MD5
sed -e s/'{{md5sum}}'/$UB_MD5/g -e s/'{{version}}'/$UB_VERSION/g plugin/template.plg > ./unBALANCE.plg
rm -rf release

git checkout $branch_name