#!/usr/bin/env bash

# BRANCH=$(git rev-parse --abbrev-ref HEAD)

REMOTE=`git remote get-url github 2> /dev/null`

if [[ -z "$REMOTE" ]]; then
	git remote add github gitjbr:jbrodriguez/unb.git
else
	git remote set_url github gitjbr:jbrodriguez/unb.git
fi

#git merge $BRANCH
git push --tags github master
