#!/usr/bin/env bash

function error {
  echo -e "$1" >&2
  exit 1
}

# current dir is ~/builds/1f7de598/0/jbrodriguez/unbalance
npm-git-lock --repo gitlab:jbrodriguez/unbalance-modules.git -v
gom install -v

# move two folders up to ~/builds/1f7de598/0
cd ../..

# store current dir, which will become gopath ~/builds/1f7de598/0
CURRENT_DIR=`pwd`

# set golang env: ~/builds/1f7de598/0/src/jbrodriguez/unbalance
mkdir -p src/jbrodriguez
mv jbrodriguez/unbalance src/jbrodriguez/unbalance

# let's go to new starting folder: ~/builds/1f7de598/0/src/jbrodriguez/unbalance
cd src/jbrodriguez/unbalance

# compile with a temp gopath
GOPATH="$CURRENT_DIR" ./bundle

if [ $? -ne 0 ]; then
	error "Unable to create release. Please check and try again"
fi

cd $CURRENT_DIR
mv src/jbrodriguez/unbalance jbrodriguez/unbalance
rm -rf src/jbrodriguez
