#!/bin/bash
# read our configuration
source /boot/config/plugins/unbalanced/unbalanced.cfg

vars="/boot/config/plugins/unbalanced/unbalanced.env"
auth_vars="/boot/config/plugins/unbalanced/unbalanced.auth.env"
prog="/usr/local/emhttp/plugins/unbalanced/unbalanced"

# stop it if it's running
killall unbalanced > /dev/null 2>&1

# run the app
nohup sudo -H bash -c "set -a; source \"$vars\"; [ -f \"$auth_vars\" ] && source \"$auth_vars\"; set +a; \"$prog\" --port \"$PORT\"" > /dev/null 2>&1 &
