#!/bin/bash
# read our configuration
source /boot/config/plugins/unbalanced/unbalanced.cfg

# read our env vars
source /boot/config/plugins/unbalanced/unbalanced.env 2> /dev/null || true

prog="/usr/local/emhttp/plugins/unbalanced/unbalanced"

# stop it if it's running
killall unbalanced > /dev/null 2>&1

# run the app
nohup sudo -H bash -c "$prog --port $PORT" > /dev/null 2>&1 &
