#!/usr/bin/env bash

function error {
  echo -e "$1" >&2
  exit 1
}

UB_RELEASE="release/unbalance"
UB_VERSION=$(cat VERSION)
UB_FILE="unbalance-$UB_VERSION.tgz"
echo $UB_FILE


if [ -f "$UB_FILE" ]; then
	echo -e "Bundle $UB_FILE already exists. No further actions will be taken." >&2
	exit 0
fi

if ! git diff --quiet; then
	error "There are unsaved changes in your current branch. Please commit changes and try again."
fi

# branch_name=$(git symbolic-ref -q HEAD)
# branch_name=${branch_name##refs/heads/}
# branch_name=${branch_name:-HEAD}
#
# git checkout master
#
# if ! git diff --quiet; then
# 	git checkout $branch_name
# 	error "There are unsaved changes in master. Please commit changes and try again."
# fi

echo "Building client"
npm run build

if [ $? -ne 0 ]; then
	error "Unable to build client. Please check and try again"
fi

echo "Building server"
make server

if [ $? -ne 0 ]; then
	error "Unable to build server. Please check and try again"
fi


echo "Generating release ..."
rm -rf release && mkdir -p $UB_RELEASE
cp -r dist/* $UB_RELEASE
cp -r plugin/event $UB_RELEASE
cp -r plugin/scripts $UB_RELEASE
cp -r plugin/images $UB_RELEASE
cp plugin/README.md $UB_RELEASE
cp plugin/unbalance.png $UB_RELEASE
cp plugin/unbalance.page $UB_RELEASE
cp CHANGES $UB_RELEASE
cp VERSION $UB_RELEASE

pushd release
tar czvf ./$UB_FILE unbalance
mv ./$UB_FILE ..
popd

UB_MD5=$(md5sum ./$UB_FILE | cut -d' ' -f1)
echo "MD5: ${UB_MD5}"

CHANGES=`cat changelogs/${UB_VERSION}.txt 2> /dev/null`

sed -e s/'{{md5}}'/$UB_MD5/g -e s/'{{version}}'/$UB_VERSION/g -e s/'{{changes}}'/$CHANGES/g plugin/template.plg > ./unbalance.plg
rm -rf release

echo "Succesfully generated unbalance-$UB_VERSION"
