#!/bin/bash

rm -rf ./dist
rm -rf ./client/dist

TARGET="${1:-all}"
SERVER="${2:-wopr}"

if [ $TARGET == 'all' ] || [ $TARGET == 'client' ] ; then
	pushd client
	npm run build
	popd
fi

if [ $TARGET == 'all' ] || [ $TARGET == 'server' ] ; then
	pushd server
	make server
	popd
fi

rsync -avzP -e "ssh" client/dist/* $SERVER:/usr/local/emhttp/plugins/unbalance/app
rsync -avzP -e "ssh" client/dist/index.html $SERVER:/usr/local/emhttp/plugins/unbalance
rsync -avzP -e "ssh" dist/* $SERVER:/usr/local/emhttp/plugins/unbalance/