#!/usr/bin/env bash

function error {
	NAME=$1

	printf "$1"
	exit 1
}

PROG="unbalance"

# current dir is ~/.cix/builds/jbrodriguez/unbalance
ORIGINAL_DIR=`pwd`

# move two folders up to ~/.cix/builds
cd ../..

# store current dir, which will become gopath ~/.cix/builds
CURRENT_DIR=`pwd`

# set golang env: ~/.cix/builds/src/jbrodriguez/unbalance
rm -rf src
mkdir -p src/jbrodriguez/unbalance
mv jbrodriguez/unbalance src/jbrodriguez

# let's go to new starting folder: ~/.cix/builds/src/jbrodriguez/unbalance
cd src/jbrodriguez/unbalance

pushd client
npm install
pushd node_modules/react-tree-menu
npm install
popd
popd

pushd server
GOPATH="$CURRENT_DIR" dep ensure
popd

# compile with a temp gopath
GOPATH="$CURRENT_DIR" scripts/bundle

if [ $? -ne 0 ]; then
	cd $CURRENT_DIR
	mv src/jbrodriguez/unbalance jbrodriguez
	rm -rf src
	cd $ORIGINAL_DIR

	error "Unable to create release. Please check and try again"
fi

cd $CURRENT_DIR
mv src/jbrodriguez/unbalance jbrodriguez
rm -rf src
cd $ORIGINAL_DIR

echo "Successfully generated $PROG unRAID plugin"
