#!/usr/bin/env bash

function error {
  echo -e "$1" >&2
  exit 1
}

# This sections deals with pushing the current tag
# to the unbalance github repo
REMOTE=`git remote get-url github 2> /dev/null`
if [[ -z "$REMOTE" ]]; then
	git remote add github gitjbr:jbrodriguez/unb.git
else
	git remote set_url github gitjbr:jbrodriguez/unb.git
fi

TAG=`git describe --abbrev=0 --tags 2> /dev/null`
if [[ -z "$TAG" ]]; then
	error "Unable to retrieve latest tag"
fi

git push github ${TAG}
if [ $? -ne 0 ]; then
	error "Unable to push tag ${TAG} to github"
fi
