#!/usr/bin/env bash

function error {
	NAME=$1

	printf "$1"
	exit 1
}

PROG="unbalance"

# install client dependencies
pushd client
npm install
pushd node_modules/react-tree-menu
npm install
popd
popd


# this builds both client and server
scripts/bundle

if [ $? -ne 0 ]; then
	error "Unable to create release. Please check and try again"
fi

echo "Successfully generated $PROG unRAID plugin"
