#!/usr/bin/env bash

set -e

# This section deals with updating the plg in the unraid repo
VERSION=`cat VERSION 2> /dev/null`
if [[ -z "$VERSION" ]]; then
	error "Unable to retrieve latest version"
fi

rm -rf unraid
git clone https://github.com/jbrodriguez/unraid.git

pushd unraid

git remote set-url origin gitjbr:jbrodriguez/unraid.git
git checkout master
cat ../unbalance.plg > plugins/unbalance.plg
git add -A
git commit -m "Update version to ${VERSION}"
git push origin master

popd
