#!/bin/bash

patch="${1:-}"

# Get the current date in the specified format
version=$(date '+%Y.%m.%d')

make local
tar -cvzf unbalanced-$version$patch.tgz unbalanced

# Calculate the MD5 checksum for the plugin
md5=$(md5sum "$name-$version.tgz" | awk '{print $1}')

# Get the latest git tag
latest_tag=$(git describe --tags --abbrev=0)

# Generate the changelog since the latest tag
changes=$(git log --oneline "$latest_tag"..HEAD --pretty="- %s")

# Replace placeholders in the template.xml and output to plugin.xml
sed -e "s/##version##/$version/g" \
    -e "s/##md5##/$md5/g" \
    -e "s/##changes##/$changes/g" metadata/template/unbalanced.plg > unbalanced.plg

ls -al

cat unbalanced.plg

