#!/bin/bash

patch="${1:-}"

name="unbalanced"

# Get the current date in the specified format
version=$(date '+%Y.%m.%d')

# make local
cd ui && npm run build && cd ..
go build fmt
go build -ldflags "-X main.Version=$version$patch" -v -o $name

tar -cvzf $name-$version$patch.tgz $name

# Calculate the MD5 checksum for the plugin
md5=$(md5sum $name-$version$patch.tgz | awk '{print $1}')

# Get the latest git tag
latest_tag=$(git describe --tags --abbrev=0)

# Generate the changelog since the latest tag
changes=$(git log --oneline $latest_tag..HEAD --pretty="- %s" | awk '{printf "%s\\n", $0}')

echo "changes ... ($changes)"

# Replace placeholders in the template.xml and output to plugin.xml
sed -e "s###version###$version#g" \
    -e "s###md5###$md5#g" \
    -e "s###changes###$changes#g" \
    metadata/template/$name.plg > $name.plg

ls -al

cat $name.plg

