#!/bin/bash

patch="${1:-}"

# Get the latest tag in the repository
latest_tag=$(git describe --tags --abbrev=0)

# Generate the changelog using the git log command
changelog=$(git log --oneline 30eb92a..HEAD --pretty="- %s")

# Get the current date
mb_date=$(date '+%Y.%m.%d')

# Replace the placeholder in the XML template with the changelog
sed -e "/&changes;/r /dev/stdin" -e "/&changes;/d" template.xml > output.xml <<EOF
${changelog}
EOF

make local
tar -cvzf unbalanced-$(mb_date)$(patch).tgz unbalanced
md5sum unbalanced-$(mb_date)$(patch).tgz
ls -al
